---
title: "I Asked a Java Champion: What Is the Biggest Problem That Professional Java Developers Are Facing Today?"
date: 2021-10-26
draft: false
---
= I Asked a Java Champion: What Is the Biggest Problem That Professional Java Developers Are Facing Today?
Marko Milenkovic
2021-10-26

I have attended the workshop that is organized by the https://itkonekt.com/en/[ITKonekt]. The workshop was about efficient coding practices for best performance in Java. Java Champion https://victorrentea.ro/[Victor Rentea] did a great job explaining all java internals, tools, hibernate, threads, collections, garbage collections, and much more. It was very enjoyable to learn from him, and I decided to ask him the question:

[quote]
____
What is the biggest problem that professional Java developers are facing today?
____

His initial answer was: "Not writing enough Java. They write Kubernetes scripts, dev-ops scripts, python scripts…"

My understanding of this is that those people are very experienced developers. He also mentioned that this is what his colleagues are working on currently. But if you are just starting your career, he has advice for you:

* If you are starting a career, then you should learn the language and frameworks that you are using. You should master the language and frameworks. This is the first challenge.
* Don't be disgusted by the front-end technologies, try to be full stack after you master Java. This is after you are comfortable with Java. Go a bit full stack, not "full full" stack, but "just a bit" full stack.
* Try to learn more about what surrounds you. Learn some other language. Kotlin is a good one.
* Learn dev ops. Try to learn a bit of everything.

He also gave me this advice:

As long as you are surrounded by people smarter than you, you are good. And as long as you love to work with your team, you are good. Doesn't matter project or technology, it can be a terrible legacy system. If you have super cool surroundings, and you keep learning, and you keep having fun, it's perfect.

If you liked this post, you can follow me on https://twitter.com/mare_milenkovic[Twitter], or https://www.linkedin.com/in/marko-milenkovic-48320b59/[LinkedIn].

Victor is a great trainer and one of the best presenters. You can find him at the following links:

* Website http://victorrentea.ro/[victorrentea.ro] you can find a *blog*, *recorded talks*, plus other *goodies*.
* https://www.meetup.com/bucharest-software-craftsmanship-community/[Bucharest-software-craftsmanship-community] (3000+ developers).
* https://twitter.com/victorrentea[Twitter], http://www.linkedin.com/in/victor-rentea-trainer[LinkedIn], https://fb.me/VictorRentea.ro[Facebook].
* https://youtube.com/vrentea[Victor's YouTube Channel] - here you can find more recorded and live content, including coding katas, recordings of past meetups, and more.
